name: Buid, create and push docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_create_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
              
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      

    - name: Build the Docker image   
      run: docker build . --file Dockerfile --tag arunthegen/javawebapp:latest
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker push   
      run: docker push arunthegen/javawebapp:latest   
